### ISSUE TITLE
Cursor can be misplaced in some line wrapping situations

### ISSUE THREAD

**Issue by jetmind** [sparksuite/simplemde-markdown-editor#39] opened 2015-08-06 12:37 UTC
https://jsfiddle.net/zjxnwroL/8/
1. Place cursor in the end of the first list item (i.e. after "indexation")
2. Type one character (e.g. "q")
3. Remove it (backspace)
4. Move cursor down one line using keyboard and type something

Note, after (3) cursor is already in wrong position, but if you proceed typing/deleting it will fix itself. Seems like (4) messes it up completely

Plain CodeMirror does not have this kind of bug https://jsfiddle.net/o335vwsw/6/

I've tried to [compress](http://codemirror.net/doc/compress.html) CodeMirror to include 'gfm' mode and create a jsfiddle with it, but it does not work for me (see console output [here](https://jsfiddle.net/o335vwsw/5/))

It might be a problem related to gfm mode, but I'm not sure.

**Comment by WesCossick** [comment] 2015-08-06 16:37
Still looking into why this is... Your second CodeMirror is just a plain text box. To use GFM mode, you'll need the markdown.js dependency and the overlay.js dependency.

**Comment by WesCossick** [comment] 2015-08-06 16:45
Here's a working pure CodeMirror JSFiddle: https://jsfiddle.net/nt9su05v/

**Comment by danabrey** [comment] 2015-08-07 08:20
I think this may be related to a similar issue I've been having when there is a lot of content in the editor, including at least one link (or possibly other inline markup too). e.g. https://jsfiddle.net/zntgjp1b/3/ - scroll right to the bottom of the page and attempt to change some content.

The line-wrapping seems to mess up the cursor position - it's almost as though CodeMirror thinks that the line is shorter or longer than it is.

**Comment by danabrey** [comment] 2015-08-07 08:57
Doing a bit of digging, I found [this](https://discuss.atom.io/t/cursor-appears-to-be-displayed-one-character-to-the-right-of-its-actual-position/1452/13) Atom support request and its related [GitHub discussion](https://github.com/atom/atom/issues/6055) about Chrome measuring character widths in strange and exciting ways. Using a monospace font indeed fixes both this issue and my example:

https://jsfiddle.net/zjxnwroL/9/
https://jsfiddle.net/zntgjp1b/4/

**Comment by jetmind** [comment] 2015-08-07 09:10
@danabrey No, it doesn't. Change the width to 630px, so that first list item would fit in one line and typing one more character will wrap and issue is still there

https://jsfiddle.net/zjxnwroL/10/

**Comment by danabrey** [comment] 2015-08-07 10:28
You're right. It's intermittent and hadn't occurred on multiple refreshes when I tested it.

One of the situations where a cursor problem is always triggered in my testing is when you highlight text which includes a whole link, and replace it by typing.

**Comment by danabrey** [comment] 2015-08-07 10:55
Reverting to version 1.3.1 has fixed the cursor issues in testing for me.

**Comment by WesCossick** [comment] 2015-08-07 17:31
Interesting, I can confirm that v1.3.1 does not experience this issue. This leads me to believe that CodeMirror is to blame, specifically the update to v5.5.1. I'm wondering if I build the simplemde.min.js file with the latest CodeMirror commits if they've noticed this and corrected it.

**Comment by WesCossick** [comment] 2015-08-07 21:01
Upon further testing, the move from CodeMirror 5.4 to 5.5 is the cause of the issue. The latest build of CodeMirror 5.5 using all of the latest commits does not fix the issue.

**Comment by WesCossick** [comment] 2015-08-08 18:26
Adding the codemirror.css as an external resource before simplemde.min.css fixes the issue. See https://jsfiddle.net/zjxnwroL/11/

It causes some other incorrect styling issues, but I'm working on that now.

**Comment by WesCossick** [comment] 2015-08-08 20:00
Fixed. Will be released in v1.5.0.

**Closed as completed by WesCossick** 2015-08-08 20:00 UTC
Labels: bug

**Comment by danabrey** [comment] 2015-08-08 21:53
Great!

**Comment by jetmind** [comment] 2015-08-11 13:12
Cool! Thanks for your prompt reaction!
