### ISSUE TITLE
It's own class namespace

### ISSUE THREAD

**Issue by rasmuseeg** [sparksuite/simplemde-markdown-editor#354] opened 2016-06-08 18:15 UTC
All classes should target everything related to simplmde, and not every CodeMirror editor on the page?

Like so: 

```
/**
 * simplemde v1.10.1
 * Copyright Next Step Webs, Inc.
 * @link https://github.com/NextStepWebs/simplemde-markdown-editor
 * @license MIT
 */
.simplemde .CodeMirror {
  color: #000;
}
.simplemde .CodeMirror-lines {
  padding: 4px 0;
}
.simplemde .CodeMirror pre {
  padding: 0 4px;
}
.simplemde .CodeMirror-gutter-filler,
.simplemde .CodeMirror-scrollbar-filler {
  background-color: #fff;
}
.simplemde .CodeMirror-gutters {
  border-right: 1px solid #ddd;
  background-color: #f7f7f7;
  white-space: nowrap;
}
.simplemde .CodeMirror-linenumber {
  padding: 0 3px 0 5px;
  min-width: 20px;
  text-align: right;
  color: #999;
  white-space: nowrap;
}
.simplemde .CodeMirror-guttermarker {
  color: #000;
}
.simplemde .CodeMirror-guttermarker-subtle {
  color: #999;
}
.simplemde .CodeMirror-cursor {
  border-left: 1px solid #000;
  border-right: none;
  width: 0;
}
.simplemde .CodeMirror div.CodeMirror-secondarycursor {
  border-left: 1px solid silver;
}
.simplemde .cm-fat-cursor .CodeMirror-cursor {
  width: auto;
  border: 0;
  background: #7e7;
}
.simplemde .cm-fat-cursor div.CodeMirror-cursors {
  z-index: 1;
}
.simplemde .cm-animate-fat-cursor {
  width: auto;
  border: 0;
  -webkit-animation: blink 1.06s steps(1) infinite;
  -moz-animation: blink 1.06s steps(1) infinite;
  animation: blink 1.06s steps(1) infinite;
  background-color: #7e7;
}
@-moz-keyframes blink {
  50% {
    background-color: transparent;
  }
}
@-webkit-keyframes blink {
  50% {
    background-color: transparent;
  }
}
@keyframes blink {
  50% {
    background-color: transparent;
  }
}
.simplemde .cm-tab {
  display: inline-block;
  text-decoration: inherit;
}
.simplemde .CodeMirror-ruler {
  border-left: 1px solid #ccc;
  position: absolute;
}
.simplemde .cm-s-default .cm-header {
  color: #00f;
}
.simplemde .cm-s-default .cm-quote {
  color: #090;
}
.simplemde .cm-negative {
  color: #d44;
}
.simplemde .cm-positive {
  color: #292;
}
.simplemde .cm-header,
.simplemde .cm-strong {
  font-weight: 700;
}
.simplemde .cm-em {
  font-style: italic;
}
.simplemde .cm-link {
  text-decoration: underline;
}
.simplemde .cm-strikethrough {
  text-decoration: line-through;
}
.simplemde .cm-s-default .cm-keyword {
  color: #708;
}
.simplemde .cm-s-default .cm-atom {
  color: #219;
}
.simplemde .cm-s-default .cm-number {
  color: #164;
}
.simplemde .cm-s-default .cm-def {
  color: #00f;
}
.simplemde .cm-s-default .cm-variable-2 {
  color: #05a;
}
.simplemde .cm-s-default .cm-variable-3 {
  color: #085;
}
.simplemde .cm-s-default .cm-comment {
  color: #a50;
}
.simplemde .cm-s-default .cm-string {
  color: #a11;
}
.simplemde .cm-s-default .cm-string-2 {
  color: #f50;
}
.simplemde .cm-s-default .cm-meta,
.simplemde .cm-s-default .cm-qualifier {
  color: #555;
}
.simplemde .cm-s-default .cm-builtin {
  color: #30a;
}
.simplemde .cm-s-default .cm-bracket {
  color: #997;
}
.simplemde .cm-s-default .cm-tag {
  color: #170;
}
.simplemde .cm-s-default .cm-attribute {
  color: #00c;
}
.simplemde .cm-s-default .cm-hr {
  color: #999;
}
.simplemde .cm-s-default .cm-link {
  color: #00c;
}
.simplemde .cm-invalidchar,
.simplemde .cm-s-default .cm-error {
  color: red;
}
.simplemde .CodeMirror-composing {
  border-bottom: 2px solid;
}
.simplemde div.CodeMirror span.CodeMirror-matchingbracket {
  color: #0f0;
}
.simplemde div.CodeMirror span.CodeMirror-nonmatchingbracket {
  color: #f22;
}
.simplemde .CodeMirror-matchingtag {
  background: rgba(255, 150, 0, 0.3);
}
.simplemde .CodeMirror-activeline-background {
  background: #e8f2ff;
}
.simplemde .CodeMirror {
  position: relative;
  overflow: hidden;
  background: #fff;
}
.simplemde .CodeMirror-scroll {
  overflow: scroll !important;
  margin-bottom: -30px;
  margin-right: -30px;
  padding-bottom: 30px;
  height: 100%;
  outline: 0;
  position: relative;
}
.simplemde .CodeMirror-sizer {
  position: relative;
  border-right: 30px solid transparent;
}
.simplemde .CodeMirror-gutter-filler,
.simplemde .CodeMirror-hscrollbar,
.simplemde .CodeMirror-scrollbar-filler,
.simplemde .CodeMirror-vscrollbar {
  position: absolute;
  z-index: 6;
  display: none;
}
.simplemde .CodeMirror-vscrollbar {
  right: 0;
  top: 0;
  overflow-x: hidden;
  overflow-y: scroll;
}
.simplemde .CodeMirror-hscrollbar {
  bottom: 0;
  left: 0;
  overflow-y: hidden;
  overflow-x: scroll;
}
.simplemde .CodeMirror-scrollbar-filler {
  right: 0;
  bottom: 0;
}
.simplemde .CodeMirror-gutter-filler {
  left: 0;
  bottom: 0;
}
.simplemde .CodeMirror-gutters {
  position: absolute;
  left: 0;
  top: 0;
  z-index: 3;
}
.simplemde .CodeMirror-gutter {
  white-space: normal;
  height: 100%;
  display: inline-block;
  vertical-align: top;
  margin-bottom: -30px;
}
.simplemde .CodeMirror-gutter-wrapper {
  position: absolute;
  z-index: 4;
  background: 0 0 !important;
  border: none !important;
  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;
}
.simplemde .CodeMirror-gutter-background {
  position: absolute;
  top: 0;
  bottom: 0;
  z-index: 4;
}
.simplemde .CodeMirror-gutter-elt {
  position: absolute;
  cursor: default;
  z-index: 4;
}
.simplemde .CodeMirror-lines {
  cursor: text;
  min-height: 1px;
}
.simplemde .CodeMirror,
.simplemde .CodeMirror-scroll {
  min-height: 300px;
}
.simplemde .CodeMirror pre {
  -moz-border-radius: 0;
  -webkit-border-radius: 0;
  border-radius: 0;
  border-width: 0;
  background: 0 0;
  font-family: inherit;
  font-size: inherit;
  margin: 0;
  white-space: pre;
  word-wrap: normal;
  line-height: inherit;
  color: inherit;
  z-index: 2;
  position: relative;
  overflow: visible;
  -webkit-tap-highlight-color: transparent;
}
.simplemde .CodeMirror-wrap pre {
  word-wrap: break-word;
  white-space: pre-wrap;
  word-break: normal;
}
.simplemde .CodeMirror-linebackground {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  z-index: 0;
}
.simplemde .CodeMirror-linewidget {
  position: relative;
  z-index: 2;
  overflow: auto;
}
.simplemde .CodeMirror-code {
  outline: 0;
}
.simplemde .CodeMirror-gutter,
.simplemde .CodeMirror-gutters,
.simplemde .CodeMirror-linenumber,
.simplemde .CodeMirror-scroll,
.simplemde .CodeMirror-sizer {
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
.simplemde .CodeMirror-measure {
  position: absolute;
  width: 100%;
  height: 0;
  overflow: hidden;
  visibility: hidden;
}
.simplemde .CodeMirror-cursor {
  position: absolute;
}
.simplemde .CodeMirror-measure pre {
  position: static;
}
.simplemde div.CodeMirror-cursors {
  visibility: hidden;
  position: relative;
  z-index: 3;
}
.simplemde .CodeMirror-focused div.CodeMirror-cursors,
.simplemde div.CodeMirror-dragcursors {
  visibility: visible;
}
.simplemde .CodeMirror-selected {
  background: #d9d9d9;
}
.simplemde .CodeMirror-focused .CodeMirror-selected,
.simplemde .CodeMirror-line::selection,
.simplemde .CodeMirror-line > span::selection,
.simplemde .CodeMirror-line > span > span::selection {
  background: #d7d4f0;
}
.simplemde .CodeMirror-crosshair {
  cursor: crosshair;
}
.simplemde .CodeMirror-line::-moz-selection,
.simplemde .CodeMirror-line > span::-moz-selection,
.simplemde .CodeMirror-line > span > span::-moz-selection {
  background: #d7d4f0;
}
.simplemde .cm-searching {
  background: #ffa;
  background: rgba(255, 255, 0, 0.4);
}
.simplemde .cm-force-border {
  padding-right: .1px;
}
@media print {
  .simplemde .CodeMirror div.CodeMirror-cursors {
    visibility: hidden;
  }
}
.simplemde .cm-tab-wrap-hack:after {
  content: '';
}
.simplemde span.CodeMirror-selectedtext {
  background: 0 0;
}
.simplemde .CodeMirror {
  height: auto;
  border: 1px solid #ddd;
  border-bottom-left-radius: 4px;
  border-bottom-right-radius: 4px;
  padding: 10px;
  font: inherit;
  z-index: 1;
}
.simplemde .CodeMirror-fullscreen {
  background: #fff;
  position: fixed !important;
  top: 50px;
  left: 0;
  right: 0;
  bottom: 0;
  height: auto;
  z-index: 9;
}
.simplemde .CodeMirror-sided {
  width: 50% !important;
}
.simplemde .editor-toolbar {
  position: relative;
  opacity: .6;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  -o-user-select: none;
  user-select: none;
  padding: 0 10px;
  border-top: 1px solid #bbb;
  border-left: 1px solid #bbb;
  border-right: 1px solid #bbb;
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
}
.simplemde .editor-toolbar:after,
.simplemde .editor-toolbar:before {
  display: block;
  content: ' ';
  height: 1px;
}
.simplemde .editor-toolbar:before {
  margin-bottom: 8px;
}
.simplemde .editor-toolbar:after {
  margin-top: 8px;
}
.simplemde .editor-toolbar:hover,
.simplemde .editor-wrapper input.title:focus,
.simplemde .editor-wrapper input.title:hover {
  opacity: .8;
}
.simplemde .editor-toolbar.fullscreen {
  width: 100%;
  height: 50px;
  overflow-x: auto;
  overflow-y: hidden;
  white-space: nowrap;
  padding-top: 10px;
  padding-bottom: 10px;
  box-sizing: border-box;
  background: #fff;
  border: 0;
  position: fixed;
  top: 0;
  left: 0;
  opacity: 1;
  z-index: 9;
}
.simplemde .editor-toolbar.fullscreen::before {
  width: 20px;
  height: 50px;
  background: -moz-linear-gradient(left, #ffffff 0, rgba(255, 255, 255, 0) 100%);
  background: -webkit-gradient(linear, left top, right top, color-stop(0, #ffffff), color-stop(100%, rgba(255, 255, 255, 0)));
  background: -webkit-linear-gradient(left, #ffffff 0, rgba(255, 255, 255, 0) 100%);
  background: -o-linear-gradient(left, #ffffff 0, rgba(255, 255, 255, 0) 100%);
  background: -ms-linear-gradient(left, #ffffff 0, rgba(255, 255, 255, 0) 100%);
  background: linear-gradient(to right, #ffffff 0, rgba(255, 255, 255, 0) 100%);
  position: fixed;
  top: 0;
  left: 0;
  margin: 0;
  padding: 0;
}
.simplemde .editor-toolbar.fullscreen::after {
  width: 20px;
  height: 50px;
  background: -moz-linear-gradient(left, rgba(255, 255, 255, 0) 0, #ffffff 100%);
  background: -webkit-gradient(linear, left top, right top, color-stop(0, rgba(255, 255, 255, 0)), color-stop(100%, #ffffff));
  background: -webkit-linear-gradient(left, rgba(255, 255, 255, 0) 0, #ffffff 100%);
  background: -o-linear-gradient(left, rgba(255, 255, 255, 0) 0, #ffffff 100%);
  background: -ms-linear-gradient(left, rgba(255, 255, 255, 0) 0, #ffffff 100%);
  background: linear-gradient(to right, rgba(255, 255, 255, 0) 0, #ffffff 100%);
  position: fixed;
  top: 0;
  right: 0;
  margin: 0;
  padding: 0;
}
.simplemde .editor-toolbar a {
  display: inline-block;
  text-align: center;
  text-decoration: none !important;
  color: #2c3e50 !important;
  width: 30px;
  height: 30px;
  margin: 0;
  border: 1px solid transparent;
  border-radius: 3px;
  cursor: pointer;
}
.simplemde .editor-toolbar a.active,
.simplemde .editor-toolbar a:hover {
  background: #fcfcfc;
  border-color: #95a5a6;
}
.simplemde .editor-toolbar a:before {
  line-height: 30px;
}
.simplemde .editor-toolbar i.separator {
  display: inline-block;
  width: 0;
  border-left: 1px solid #d9d9d9;
  border-right: 1px solid #fff;
  color: transparent;
  text-indent: -10px;
  margin: 0 6px;
}
.simplemde .editor-toolbar a.fa-header-x:after {
  font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
  font-size: 65%;
  vertical-align: text-bottom;
  position: relative;
  top: 2px;
}
.simplemde .editor-toolbar a.fa-header-1:after {
  content: "1";
}
.simplemde .editor-toolbar a.fa-header-2:after {
  content: "2";
}
.simplemde .editor-toolbar a.fa-header-3:after {
  content: "3";
}
.simplemde .editor-toolbar a.fa-header-bigger:after {
  content: "▲";
}
.simplemde .editor-toolbar a.fa-header-smaller:after {
  content: "▼";
}
.simplemde .editor-toolbar.disabled-for-preview a:not(.no-disable) {
  pointer-events: none;
  background: #fff;
  border-color: transparent;
  text-shadow: inherit;
}
@media only screen and (max-width: 700px) {
  .simplemde .editor-toolbar a.no-mobile {
    display: none;
  }
}
.simplemde .editor-statusbar {
  padding: 8px 10px;
  font-size: 12px;
  color: #959694;
  text-align: right;
}
.simplemde .editor-statusbar span {
  display: inline-block;
  min-width: 4em;
  margin-left: 1em;
}
.simplemde .editor-preview,
.simplemde .editor-preview-side {
  padding: 10px;
  background: #fafafa;
  overflow: auto;
  display: none;
  box-sizing: border-box;
}
.simplemde .editor-statusbar .lines:before {
  content: 'lines: ';
}
.simplemde .editor-statusbar .words:before {
  content: 'words: ';
}
.simplemde .editor-statusbar .characters:before {
  content: 'characters: ';
}
.simplemde .editor-preview {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  z-index: 7;
}
.simplemde .editor-preview-side {
  position: fixed;
  bottom: 0;
  width: 50%;
  top: 50px;
  right: 0;
  z-index: 9;
  border: 1px solid #ddd;
}
.simplemde .editor-preview-active,
.simplemde .editor-preview-active-side {
  display: block;
}
.simplemde .editor-preview-side > p,
.simplemde .editor-preview > p {
  margin-top: 0;
}
.simplemde .editor-preview pre,
.simplemde .editor-preview-side pre {
  background: #eee;
  margin-bottom: 10px;
}
.simplemde .editor-preview table td,
.simplemde .editor-preview table th,
.simplemde .editor-preview-side table td,
.simplemde .editor-preview-side table th {
  border: 1px solid #ddd;
  padding: 5px;
}
.simplemde .CodeMirror .CodeMirror-code .cm-tag {
  color: #63a35c;
}
.simplemde .CodeMirror .CodeMirror-code .cm-attribute {
  color: #795da3;
}
.simplemde .CodeMirror .CodeMirror-code .cm-string {
  color: #183691;
}
.simplemde .CodeMirror .CodeMirror-selected {
  background: #d9d9d9;
}
.simplemde .CodeMirror .CodeMirror-code .cm-header-1 {
  font-size: 200%;
  line-height: 200%;
}
.simplemde .CodeMirror .CodeMirror-code .cm-header-2 {
  font-size: 160%;
  line-height: 160%;
}
.simplemde .CodeMirror .CodeMirror-code .cm-header-3 {
  font-size: 125%;
  line-height: 125%;
}
.simplemde .CodeMirror .CodeMirror-code .cm-header-4 {
  font-size: 110%;
  line-height: 110%;
}
.simplemde .CodeMirror .CodeMirror-code .cm-comment {
  background: rgba(0, 0, 0, 0.05);
  border-radius: 2px;
}
.simplemde .CodeMirror .CodeMirror-code .cm-link {
  color: #7f8c8d;
}
.simplemde .CodeMirror .CodeMirror-code .cm-url {
  color: #aab2b3;
}
.simplemde .CodeMirror .CodeMirror-code .cm-strikethrough {
  text-decoration: line-through;
}
.simplemde .CodeMirror .CodeMirror-placeholder {
  opacity: .5;
}
.simplemde .CodeMirror .cm-spell-error:not(.cm-url):not(.cm-comment):not(.cm-tag):not(.cm-word) {
  background: rgba(255, 0, 0, 0.15);
}

```

**Comment by WesCossick** [comment] 2016-06-08 18:36
Duplicate of #318

**Closed as completed by WesCossick** 2016-06-08 18:36 UTC
Labels: duplicate
