### ISSUE TITLE
Preview Toggle

### ISSUE THREAD

**Issue by Xarcell** [sparksuite/simplemde-markdown-editor#116] opened 2015-09-26 02:03 UTC
I like the preview toggle, but I don't like that it forces fullscreen. Can you change it so that it shows preview without going fullscreen?

This is a very sharp editor by the way. Well done.

**Comment by WesCossick** [comment] 2015-09-26 03:18
Are you referring to the side by side preview toggle forcing fullscreen?

**Comment by Xarcell** [comment] 2015-09-26 11:55
Yes sir.

**Comment by WesCossick** [comment] 2015-09-26 17:04
Duplicate of #90

**Closed as completed by WesCossick** 2015-09-26 17:04 UTC
Labels: duplicate
