### ISSUE TITLE
 CodeMirror is not defined....when i use simplemde with webpack

### ISSUE THREAD

**Issue by Archao-ME** [sparksuite/simplemde-markdown-editor#358] opened 2016-06-11 20:10 UTC
when i use it to my code with webpack, there first problem is : 

> Module not found: Error: Cannot resolve module 'fs'

and i fixed it in webpack config file..with add 

```
  node: {
    fs: "empty"
  },
```

But now it show error like that : 

> spell-checker.js?5142:19Uncaught ReferenceError: CodeMirror is not defined

how can i fix it??

**Comment by robbieaverill** [comment] 2016-06-12 20:36
Duplicate of #355

**Closed as completed** 2016-06-14 16:10 UTC
Labels: duplicate
