### ISSUE TITLE
Italic button issues

### ISSUE THREAD

**Issue by fkamras** [sparksuite/simplemde-markdown-editor#307] opened 2016-04-28 08:20 UTC
When the italic button is clicked the bold button gets highlighted.
Also if after that, the bold icon is clicked it goes to the beginning of the row instead of adding the markdown for bold.

**Comment by danabrey** [comment] 2016-04-28 09:21
I can reproduce this if I click the italic button without any content highlighted. It looks like it's creating the italic syntax (`*` and `*`) around nothing, which causes `**` to be inserted at the cursor position. This is (both correctly and mistakenly) taken as being the beginning of a block of bold text.

A possible solution would be to force a space between the asterisks if no text is selected, i.e. `* *` instead of `**`.

**Comment by danabrey** [comment] 2016-04-28 09:22
Please ignore the well-timed (now fixed) accidental markdown formatting!

**Comment by WesCossick** [comment] 2016-05-02 19:37
Don't think there's a good way around this. I'm not sure I like the idea of adding a space between the asterisks.

**Closed as completed by WesCossick** 2016-05-02 19:37 UTC
Labels: wontfix
