### ISSUE TITLE
Alternative Headers

### ISSUE THREAD

**Issue by Henni** [sparksuite/simplemde-markdown-editor#450] opened 2016-10-25 20:44 UTC
Currently the following input is rendered incorrectly:

``` markdown
test
=====
more content.....
```

![image](https://cloud.githubusercontent.com/assets/1267827/19703466/36470f96-9b04-11e6-9c43-fa69bf92d6f1.png)

Instead the word `test` should also be rendered as a heading.
The same problem occurs with `-----` which should render the line above as h2.

**Comment by WesCossick** [comment] 2016-10-26 17:18
Duplicate of https://github.com/NextStepWebs/simplemde-markdown-editor/issues/412

**Closed as completed by WesCossick** 2016-10-26 17:18 UTC
Labels: duplicate
