### ISSUE TITLE
Seems spell checker causes the problem `CodeMirror is not defnied`

### ISSUE THREAD

**Issue by royguo** [sparksuite/simplemde-markdown-editor#359] opened 2016-06-12 03:25 UTC
I don't have enough time to track this issue, but when I include `CodeMirror` before `simplemde`, and then disable `spell checker`, the problem is gone, hope this helps!

**Comment by robbieaverill** [comment] 2016-06-12 20:36
Duplicate of #355

**Closed as completed** 2016-06-14 16:10 UTC
Labels: duplicate
