### ISSUE TITLE
Statusbar doesn't update on intialization

### ISSUE THREAD

**Issue by jfly** [sparksuite/simplemde-markdown-editor#334] opened 2016-05-24 04:10 UTC
Reproduction here: https://jsfiddle.net/LncxwsLg/

See screenshot:

![2016-05-23_21 05 15_1085x660_kaladin](https://cloud.githubusercontent.com/assets/277474/15491898/42d248c4-212a-11e6-9d9c-95c3bb82b621.png)

The `<textarea>` clearly has more than 0 lines, but is showing up as 0 lines. Once I type something, the status bar updates correctly.

I haven't dug too deeply into the code, but it looks like it's at least trying to handle this [here](https://github.com/NextStepWebs/simplemde-markdown-editor/blob/6eae597a693d167a3d02c9020da779b1bece1671/src/js/simplemde.js#L1831-L1836).

**Comment by FabianKoestring** [comment] 2016-05-24 09:37
Duplicate of #299

**Comment by amanuel2** [comment] 2016-05-24 10:55
Hey everyone! Im currently activly developing a forum application in Pure AngularJS(First OpenSource Forum App.).
If anyone can contribute positvely to my project, it would be the best thing in the world!Thanks for reading my opensource project is at github located : https://github.com/amanuel2/ng-forum
 
 @FabianKoestring @FabianKoestring

**Closed as completed** 2016-06-08 01:56 UTC
Labels: duplicate
