### ISSUE TITLE
Side by side preview

### ISSUE THREAD

**Issue by nofxx** [sparksuite/simplemde-markdown-editor#47] opened 2015-08-11 16:52 UTC
Again thank you Wes, great lib.  Here is my approach of the only thing missing heh... (actually 3).

https://jsfiddle.net/xb0rbkvk/9
A split button goes to fullscreen where left is editor, right is preview. 50/50.
Preview is live updated and scrolls are synced (roll code, preview rolls too).

Not creating a PR to consult you first, JS ain't my forte. And... I (and my editor) share massive OCD, so I removed all blanks and changed tabs by spaces. 
Also added strike through (github markdown but marked supported) and tables.

**Comment by nofxx** [comment] 2015-08-11 16:55
One thing going to look over better is the css, I'm duplicating some lines wish I could share.
All preview style.  That part is anyways field for the app to customize (use the same as the result will look)

**Comment by nofxx** [comment] 2015-08-11 17:05
Ops, I'm messed it up.  
Didn't realized there was changes in the fullscreen: Rebase and... It's not working anymore hehe. 
Going to fix , but need some sleep now.

We're not going to have the fullwindow anymore? (let's call it this)
Before: button fullscreen goes 100% of the browser (fullwindow), you hit F11 native fullscreen.
Now:  button fullscreen goes to native fullscreen.

Not to mention my side by side was working both fullwindow and native! hahah.
But, rly, I kinda liked having both ways to choose.

**Comment by WesCossick** [comment] 2015-08-11 17:14
Thanks, can you set up a JSFiddle to view your side-by-side branch? You can use https://rawgit.com/ to include the dependecies from GitHub.

With the new fullscreen feature, whether you hit F11 or click the fullscreen button, it performs the same action. It will maximize to the browser window, but will not utilize the native fullscreen. This is by design because it is much quicker and more intuitive, especially for non-technical users (the target audience).

**Comment by nofxx** [comment] 2015-08-11 17:23
Wait, so `development` has actually an old behaviour?  I confirm it's impossible to have window 100%, or fullwindow, now. Button or F11 goes directly to native fullscreen.
Agree fullscreen it's not intuitive, fullwindow is way better to work with.

**Comment by WesCossick** [comment] 2015-08-11 17:39
Before v1.5.0, there was no custom functionality assigned to F11 and there was no button for fullscreen. So if you pressed F11, the browser did what it natively does, which is expand to 100% of the entire screen.

Now, both F11 and the new toolbar button do the same thing. They expand to 100% of the content window inside the browser, which is not necessarily 100% of the entire screen. This is faster and more intuitive.

**Comment by nofxx** [comment] 2015-08-11 17:52
Ah, should be my bad merge than, going to redo it. 
Back with something that works, in a few hours.
Thanks for the patience.

**Comment by WesCossick** [comment] 2015-08-11 18:16
No problem, just set up a JSFiddle when you've got everything working so that myself and others can easily view the proposed changes.

**Comment by nofxx** [comment] 2015-08-12 07:52
Here it is! https://jsfiddle.net/xb0rbkvk/9

Edit: with example text.

**Comment by WesCossick** [comment] 2015-08-12 15:02
That's pretty slick! A few things will need to be ironed out though:
- Clicking the side-by-side and then clicking elsewhere in the text removes the `.active` status from the toolbar icon. This is an easy fix.
- The scroll syncing isn't the best. If the content is longer in the preview, then when you scroll the editor to the bottom, it doesn't reach the bottom of the preview. I think you're scrolling equal distance in pixels. You should scroll equal percentages of the total height of each.
- Scrolling the preview does not scroll the editor.
- Clicking the preview button when the side-by-side is active should disable side by side.
- Right side preview background should be light gray, the same light gray that is behind the normal preview.
- Right side preview should have the light gray border on the top to match the border on the top of the left side editor.
- Toggling side-by-side on and off and fullscreen on and off several times causes cursor position issues. I haven't nailed down the exact steps that cause this yet. This one might be tough to solve.

**Comment by fraserredmond** [comment] 2015-08-12 16:58
Nice :+1: 

The tables is handy too.

FYI, the strikethrough doesn't remove if you click a second time (like bold/italic/etc do.)

**Comment by nofxx** [comment] 2015-08-12 17:34
@WesCossick working on!
- That active is tricking me! 
- % instead of pixels for scroll, great idea. Was thinking some kind of easing too.
- scroll the preview doesnt scroll the code: at first this was a feature for me, but, yeah, makes more sense to sync both. Also when you start typing scroll to where the cursor is.
- Preview when side by side: haven't thought that. It would be cool if the side kinda slide to 100%.
- Border on preview: gonna try. Did that way so it looks like it's floating over the code.
- Toggle cause position issues: checking out.

@fraserredmond ty.  How strange, bold and italic works. Checking it out too.

Thank you guys.

**Comment by nofxx** [comment] 2015-08-12 19:28
Scroll using percentage fixed.
~~Strike~~ fixed.
Borders fixed.
But no idea why the side preview btn active is gonne when you click the editor panel =/

**Comment by WesCossick** [comment] 2015-08-12 21:05
The active class disappearing needs to be corrected at [this line](https://github.com/nofxx/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L763). Currently, it is:

``` javascript
if(stat[key]) {
    el.className += ' active';
} else if(key != "fullscreen") {
    el.className = el.className.replace(/\s*active\s*/g, '');
}
```

Change it to:

``` javascript
if(stat[key]) {
    el.className += ' active';
} else if(key != "fullscreen" && key != "sidebyside") {
    el.className = el.className.replace(/\s*active\s*/g, '');
}
```

**Comment by WesCossick** [comment] 2015-08-12 21:08
Regarding sliding to preview, I'd refrain from that. Personally I'm not a big fan of animations when they're not needed. Just slows things down.

**Comment by nofxx** [comment] 2015-08-12 21:59
@WesCossick yes, it works! Missed that one.
Agree with animations, now working on the preview.

**Comment by nofxx** [comment] 2015-08-12 22:05
Preview fixed:  You're side by side, click (or shortcuts) preview, now preview is fullscreen.

Now, you click preview again, to go back: full editor or side by side?

**Comment by WesCossick** [comment] 2015-08-12 22:44
Hmm, good question. I'd say back to side-by-side. It's where they just were, so that probably makes the most sense.

**Comment by WesCossick** [comment] 2015-08-12 22:45
Once you get that done, update JSFiddle so that we can see the changes!

**Comment by nofxx** [comment] 2015-08-12 22:48
Fiddle is on autoupdate, site was off for some minutes, guess the workers are back now too.

**Comment by nofxx** [comment] 2015-08-12 22:49
Btw, this looks good, check the `overlay`: https://codemirror.net/demo/simplescrollbars.html

**Comment by nofxx** [comment] 2015-08-13 05:21
Autoscroll both ways fixed! On fiddle! https://jsfiddle.net/xb0rbkvk/9
While I was at yet, seems nice to hide the editor scroll, so I did to check you guys opinions.
Also, I took the liberty to make the preview bg I lil more bright...(#f5 to #fa iirc).

**Comment by nofxx** [comment] 2015-08-13 05:24
I'm not 100% happy with the scroll antiloop code (currently a skip_scroll var I've found on stackoverflow).
We should have some ease, debounce... may help the loop condition as well as the scroll feeling.
To you guys, I'm the JS newbie here =D (or how to get rid of a task)  
https://github.com/nofxx/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L279

**Comment by WesCossick** [comment] 2015-08-14 18:02
Thanks for updating the fiddle. Regarding the non-native scrollbars, I like to stick to the native ones as often as possible.

Looking at your fork, I see you hid the scrollbar by changing `width: 50%;` to `width: 52%;`. The editor will auto-grow so there's no scrolling, so I'm not sure what scrollbar you're hiding. Either way, the 52% is too wide and will cover up part of the text on the left side.

I think the variable is working well with one exception. On Windows Chrome (what I'm using) when I let the mouse wheel scroll one single step at a time on the preview, it only scrolls the editor every other step. May want to look into that.

**Comment by nofxx** [comment] 2015-08-14 18:20
Hey Wes, yeah it was a poor man's way to hide. 
Just to check what you guys think of only 1 scrollbar.
My idea was to look for a proper way if you guys liked it.

Looking for a better way to ease the scroll.

**Comment by WesCossick** [comment] 2015-08-14 19:11
I see. I actually like the dual scrollbars, as they indicate that both sides can be scrolled. Plus the user can click and drag the scrollbar for the side they're looking at. Different operating systems have scrollbars of different widths anyway, so it would be hard to accommodate for that.

**Comment by WesCossick** [comment] 2015-08-14 19:12
I don't think the scroll needs easing either. It should just match the scroll of the side that's currently being scrolled. Windows computers don't typically have any easing, so when easing is added it seems non-native and out-of-place.

**Comment by nofxx** [comment] 2015-08-14 19:18
Ease/debounce only for the one that's being autoscrolled, not the current panel. 
With chrome I see some flick I wish wasn't there. On firefox (just checked) it's bad. Really slow scrolling.
Both linux btw, if you could please check FF on win.

**Comment by nofxx** [comment] 2015-08-14 19:55
Fixed!! W/o debouncing. Just used 2 vars, as another stackoverflow example hehe.
Actually pretty naive of me not to think of that, only one was causing flick and FF issues.
Updating fiddle. http://jsfiddle.net/xb0rbkvk/10/  (now with actual scroll ;)

**Comment by WesCossick** [comment] 2015-08-14 20:33
That looks excellent! I'm also no longer noticing any cursor position issues, which is really good. @fraserredmond do you notice anything else that needs to be improved?

**Comment by danabrey** [comment] 2015-08-15 10:29
This is looking great!

The only tiny issue I have noticed is that when I stop scrolling with the scrollbar, there is almost always a slight ease upwards regardless of whether I was scrolling up or down. (on Chrome/Windows 7 using a touchpad). 

Otherwise, it feels totally simple and intuitive.

**Comment by WesCossick** [comment] 2015-08-15 15:16
Might be unique to the touchpad? I'm not experiencing it with a mouse wheel on Chrome or Firefox. Are you able to nail down the cause?

**Comment by danabrey** [comment] 2015-08-15 17:56
I'm not seeing it at all now, so it must have been an isolated random occurence. Marvellous!

**Comment by danabrey** [comment] 2015-08-15 18:02
Ah, found it again. Here's what I do to cause it:
1. Enter side-by-side preview mode, scroll up and down a bit
2. Enter 'normal' preview mode, scroll up and down a bit
3. Turn off preview mode
4. Enter side-by-side preview mode

Now whenever I scroll up or down (using the touchpad or a mouse), I get a tiny ease upwards by 10-20 pixels or so.

**Comment by nofxx** [comment] 2015-08-16 00:10
Could not reproduce on chrome, but in FF yes, there's some ease upwards.
It's the code view changing size, due to jsfiddle small screen I think.
Any thoughts?

EDIT: Found the issue on FF: It'll scroll to where the cursor is.
EDIT: Can't reproduce any problem when running **outside jsfiddle**. Tryed updating the link in rawgit. Not sure where's the issue. But here I can't even get the scrollbar to show on fiddle (5 commits ago). All working fine on my app. :confused:

**Comment by danabrey** [comment] 2015-08-17 13:38
I've switched to this repo for testing on the site I'm using the editor on, and the issue is present in both Chrome and Firefox. In Firefox, sometimes it locks up and refuses to let me scroll elsewhere, slowly easing upwards all the time. The window size is unrestricted (it's full-page).

Scrolling using the editor scrollbar (in the middle) doesn't seem to cause this, it's only when I use the scrollbar in the preview pane.

**Comment by WesCossick** [comment] 2015-08-17 19:36
I'm testing using [this JSFiddle](http://jsfiddle.net/xb0rbkvk/10/) on Windows 10 using a mouse and can reproduce the errors using @danabrey's four steps on both Firefox and Chrome. I also tested not using JSFiddle and the results are the same.

@nofxx have you identified the cause?

**Comment by WesCossick** [comment] 2015-08-17 19:52
The issue is this... `cm.on('update'...`, `cm.on('scroll'...`, and `previewSide.onscroll...` never stop listening, they are created every single time the side-by-side preview is brought up. Which means every changes renders multiple times, and the scrolls are processed multiple times on each side.

**Comment by WesCossick** [comment] 2015-08-17 21:36
If we can have this completely polished in the next few days, I'll release it in v1.6.0. Otherwise, it'll be included in a future release.

**Comment by nofxx** [comment] 2015-08-18 00:40
Said to you guys, JS isn't my forte (cool way to say I'm newbie). But I think  I can fix it.
Just please don't hesitate to mention/suggest anything  ;)

**Comment by WesCossick** [comment] 2015-08-18 03:54
So my initial thoughts are to move the listeners outside of the code block that handles displaying the side preview. That way the listeners are created only once each.

Alternatively, it may be possible to create a simple boolean variable outside of the scope of just that function that keeps track of whether the listeners have been created or not, and creates them only if they haven't already. This is more of a bandaid solution and I'd avoid it if possible.

**Comment by nofxx** [comment] 2015-08-19 15:50
@WesCossick done! did as you said (I hope):
Separated SimpleMDE.prototype.createSidebyside, that's run only on render/init time.
Also fixes the last bug I've found: Esc key now returns code and preview from fullscreen.

**Comment by WesCossick** [comment] 2015-08-19 19:58
Is [this JSFiddle](http://jsfiddle.net/xb0rbkvk/10/) using the latest code?

**Comment by nofxx** [comment] 2015-08-19 21:23
@WesCossick I believe it is now.

**Comment by danabrey** [comment] 2015-08-19 21:33
The issue is long-gone as far as I can tell :+1: If I'm in side-by-side preview, I can choose to switch to normal preview, but not vice-versa. Is this intentional?

**Comment by WesCossick** [comment] 2015-08-19 23:04
@danabrey I think the functionality is good now, the preview actually covers up everything on the screen and is separate from the side by side editing mode in my opinion.

@nofxx Everything is looking great for the most part! One last quip– when I am using side-by-side mode and click the normal preview button, then disable the normal preview, it doesn't return to side-by-side. It returns to just the editor.

**Comment by nofxx** [comment] 2015-08-20 17:32
@danabrey yup, full screen preview disables the toolbar actually.

@WesCossick wouldn't danabrey idea be a better fit? Maybe it's my lazyness talking but: 
If we let side by side button enabled, that'll be user choice back to side or full code. 

Or maybe both. For the side -> full -> back to side works gonna need some var of last_state_was. Agreed?

**Comment by danabrey** [comment] 2015-08-20 17:49
My personal feeling is that most of my users will prefer one or the other - side-by-side preview or full-screen preview - and they are just different forms of preview mode. It would make sense to me, usability-wise, for the behaviour to be the same for both, and to either allow switching to the other or not.

**Comment by WesCossick** [comment] 2015-08-20 20:02
I think I agree too, the more I think about it. Here's what I think is the best functionality:

| Current view | Click | Action |
| --- | --- | --- |
| SBS | SBS | Exit SBS, remain in fullscreen |
| SBS | P | Exit SBS, show full preview |
| SBS | F | Exit fullscreen and SBS |
| P | P | Exit preview |
| P | SBS | Enter fullscreen (if needed), show SBS, hide preview |
| P | F | Toggle fullscreen |

_SBS = Side By Side_
_P = Preview_
_F = Fullscreen_

We'll need to make sure that the SBS button does not become disabled during normal preview.

**Comment by WesCossick** [comment] 2015-08-26 02:01
Any update on the progress of this, @nofxx? If it's completed by Friday I'll include this new feature in v1.6.0. If it's not, I'll need to bump it back to a later version.

**Comment by nofxx** [comment] 2015-08-26 16:20
@WesCossick will work on it today or later tomorrow ;)

**Comment by nofxx** [comment] 2015-08-31 18:48
@WesCossick hey man, sorry, could not work on this on the weekend.
See you cloned, that's a relief, this merge involves the dead space clean, so very messed up.
Anyways, any help I could give I'm here. On freenode too.

**Comment by WesCossick** [comment] 2015-08-31 18:54
If I have time, I'll work on the final polishes on the fork I just made of your repository. Then I'll merge it into the the development branch of SimpleMDE.

**Comment by WesCossick** [comment] 2015-09-01 06:43
It's been merged with the development branch, with the final polishes. Feel free to fork it and test it out.

**Comment by nofxx** [comment] 2015-09-01 16:14
@WesCossick TY! Merged to update the fiddle.  http://jsfiddle.net/xb0rbkvk/14/
Also, cleaned up dead spaces.
Thanks again.

**Closed as completed** 2015-09-02 06:22 UTC
Labels: new feature, idea
