### ISSUE TITLE
Safari, iOS bug - capital letters won't turn off

### ISSUE THREAD

**Issue by lumenwrites** [sparksuite/simplemde-markdown-editor#311] opened 2016-04-28 17:18 UTC
I'm using simplemde on my iPad, and I have encountered a strange bug.

When you press a shift button on the keyboard, it's supposed to capitalize the next letter you type, and after you've typed it, following letters should go back to being lower case. But instead, after I press shift and type a letter, shift stays turned on, and all the following letters are all capital.

That makes the editor pretty much unusable on mobile.

Can you help me to fix this?

**Comment by WesCossick** [comment] 2016-05-02 19:39
Duplicate of #262

**Closed as completed by WesCossick** 2016-05-02 19:39 UTC
Labels: duplicate
